apiVersion: v1
kind: Service
metadata:
  name: api-nodeport-service  # Change the service name to something meaningful
spec:
  type: NodePort  # Change the service type to NodePort
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 31000  # Specify the nodePort value (range is 30000-32767)
  selector:
    component: api

